In [57]:
import numpy as np
from sklearn.preprocessing import StandardScaler
import pandas as pd

In [58]:
# link de datasets https://www.kaggle.com/datasets/gauravduttakiit/water-potability-prediction?select=train_dataset.csv

data = pd.read_csv('train_dataset.csv')
data

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
0,7.080795,219.674262,22210.613083,5.875041,333.775777,398.517703,11.502316,112.412210,2.994259,0
1,6.783888,193.653581,13677.106441,5.171454,323.728663,477.854687,15.056064,66.396293,3.250022,0
2,6.010618,184.558582,15940.573271,8.165222,421.486089,314.529813,20.314617,83.707938,4.867287,1
3,8.097454,218.992436,18112.284447,6.196947,333.775777,376.569803,17.746264,59.909941,4.279082,1
4,8.072612,210.269780,16843.363927,8.793459,359.516169,559.167574,17.263576,68.738989,5.082206,0
...,...,...,...,...,...,...,...,...,...,...
2288,8.124208,207.509515,26489.114701,8.540837,318.059624,431.625677,10.075598,63.984225,4.724457,0
2289,10.391942,262.741770,39116.682706,3.205786,285.728420,473.313969,13.300688,65.318816,5.771715,0
2290,7.790875,196.478712,24061.349596,6.785685,350.117254,471.518536,15.343316,44.544627,3.076214,0
2291,6.139743,168.444214,23894.136010,9.494582,318.026087,494.129125,19.116022,60.264767,3.841222,0
2292,7.080795,143.300200,16263.167465,6.229737,333.775777,503.664085,19.585497,66.396293,3.451740,1

In [59]:
# Agrega una nueva columna llamada 'day' con valores del 1 al nÃºmero de filas
num_filas = len(data)
data.insert(0, 'day', range(1, num_filas + 1))

# Guarda el DataFrame modificado de nuevo en un archivo CSV
nuevo_archivo_csv = 'nuevo_archivo.csv'
data.to_csv(nuevo_archivo_csv, index=False)

print("Columna 'day' agregada al principio exitosamente.")
data

Columna 'day' agregada al principio exitosamente.

,day,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
0,1,7.080795,219.674262,22210.613083,5.875041,333.775777,398.517703,11.502316,112.412210,2.994259,0
1,2,6.783888,193.653581,13677.106441,5.171454,323.728663,477.854687,15.056064,66.396293,3.250022,0
2,3,6.010618,184.558582,15940.573271,8.165222,421.486089,314.529813,20.314617,83.707938,4.867287,1
3,4,8.097454,218.992436,18112.284447,6.196947,333.775777,376.569803,17.746264,59.909941,4.279082,1
4,5,8.072612,210.269780,16843.363927,8.793459,359.516169,559.167574,17.263576,68.738989,5.082206,0
...,...,...,...,...,...,...,...,...,...,...,...
2288,2289,8.124208,207.509515,26489.114701,8.540837,318.059624,431.625677,10.075598,63.984225,4.724457,0
2289,2290,10.391942,262.741770,39116.682706,3.205786,285.728420,473.313969,13.300688,65.318816,5.771715,0
2290,2291,7.790875,196.478712,24061.349596,6.785685,350.117254,471.518536,15.343316,44.544627,3.076214,0
2291,2292,6.139743,168.444214,23894.136010,9.494582,318.026087,494.129125,19.116022,60.264767,3.841222,0
2292,2293,7.080795,143.300200,16263.167465,6.229737,333.775777,503.664085,19.585497,66.396293,3.451740,1

In [61]:
data = np.loadtxt('nuevo_archivo.csv', delimiter=',', skiprows=1)
X, y = data[:, 0:10], data[:, 10]
print(X.shape)
print(y.shape)

(2293, 10)
(2293,)

In [62]:

num_features = 10
val_min = np.min(X)
val_max = np.max(X)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Generar pesos directamente proporcionales a los valores de las caracterÃ­sticas en el rango [0, 700]
weights = np.linspace(val_min, val_max, num_features)

# Calcular la puntuaciÃ³n transformada Y con pesos proporcionales
Y_transformed = np.dot(X_scaled, weights)

# Normalizar los valores transformados de Y al rango [0, 1]
Y_transformed = (Y_transformed - np.min(Y_transformed)) / (np.max(Y_transformed) - np.min(Y_transformed))
Y_transformed = np.round(Y_transformed, decimals=5)

print("X_scaled.shape:", X_scaled.shape)
print("Y_transformed.shape:", Y_transformed.shape)
print("Y_transformed:", Y_transformed)

X_scaled.shape: (2293, 10)
Y_transformed.shape: (2293,)
Y_transformed: [0.61613 0.49642 0.88088 ... 0.49202 0.70344 0.62635]

In [63]:
# Combina las matrices X y Y en una sola matriz
data = np.column_stack((X, Y_transformed))

# Guarda la matriz en un archivo CSV
nombre_archivo = 'water_quality_train.csv'
np.savetxt(nombre_archivo, data, delimiter=',', header="day,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Probability", comments="")

print("Datos guardados en", nombre_archivo)

Datos guardados en water_quality_train.csv

In [65]:
data = pd.read_csv('water_quality_train.csv')
data

,day,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Probability
0,1.0,7.080795,219.674262,22210.613083,5.875041,333.775777,398.517703,11.502316,112.412210,2.994259,0.61613
1,2.0,6.783888,193.653581,13677.106441,5.171454,323.728663,477.854687,15.056064,66.396293,3.250022,0.49642
2,3.0,6.010618,184.558582,15940.573271,8.165222,421.486089,314.529813,20.314617,83.707938,4.867287,0.88088
3,4.0,8.097454,218.992436,18112.284447,6.196947,333.775777,376.569803,17.746264,59.909941,4.279082,0.61619
4,5.0,8.072612,210.269780,16843.363927,8.793459,359.516169,559.167574,17.263576,68.738989,5.082206,0.90718
...,...,...,...,...,...,...,...,...,...,...,...
2288,2289.0,8.124208,207.509515,26489.114701,8.540837,318.059624,431.625677,10.075598,63.984225,4.724457,0.62564
2289,2290.0,10.391942,262.741770,39116.682706,3.205786,285.728420,473.313969,13.300688,65.318816,5.771715,0.73880
2290,2291.0,7.790875,196.478712,24061.349596,6.785685,350.117254,471.518536,15.343316,44.544627,3.076214,0.49202
2291,2292.0,6.139743,168.444214,23894.136010,9.494582,318.026087,494.129125,19.116022,60.264767,3.841222,0.70344
2292,2293.0,7.080795,143.300200,16263.167465,6.229737,333.775777,503.664085,19.585497,66.396293,3.451740,0.62635

In [67]:
data = pd.read_csv('test_dataset.csv')
# Agrega una nueva columna llamada 'day' con valores del 1 al nÃºmero de filas
num_filas = len(data)
data.insert(0, 'day', range(1, num_filas + 1))

# Guarda el DataFrame modificado de nuevo en un archivo CSV
nuevo_archivo_csv = 'water_quality_test.csv'
data.to_csv(nuevo_archivo_csv, index=False)

print("Columna 'day' agregada al principio exitosamente.")
data

Columna 'day' agregada al principio exitosamente.

,day,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity
0,1,8.813505,236.392817,40684.390014,6.608775,303.529818,278.355123,14.576057,72.872697,4.242460
1,2,8.466013,224.174936,22523.124552,6.668868,286.943922,330.044715,17.744096,77.817804,3.946621
2,3,6.350290,190.383738,14905.393852,5.537830,333.775777,446.840605,13.983567,67.817096,4.265233
3,4,9.578227,205.748742,33080.588825,5.659848,356.698301,333.069911,16.984961,68.906088,3.419239
4,5,7.300990,182.447697,29136.338677,8.253015,333.775777,307.433303,8.730149,49.895342,4.596347
...,...,...,...,...,...,...,...,...,...,...
978,979,5.921247,200.943730,17397.402858,6.756200,279.202307,380.499818,11.255357,31.966297,3.746776
979,980,7.388519,201.057714,13921.146217,7.766495,333.775777,560.774729,14.467095,74.374018,4.409054
980,981,7.553845,212.264441,14319.401370,5.793012,362.852654,450.535910,18.176483,66.396293,4.374564
981,982,7.122637,183.402648,31295.902410,4.425026,333.775777,411.616070,14.066057,77.185792,3.750447
982,983,8.370440,231.442553,15063.814968,12.279374,333.775777,422.293819,15.027088,67.503004,3.210635

In [68]:
data = pd.read_csv('water_quality_test.csv')
data

,day,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity
0,1,8.813505,236.392817,40684.390014,6.608775,303.529818,278.355123,14.576057,72.872697,4.242460
1,2,8.466013,224.174936,22523.124552,6.668868,286.943922,330.044715,17.744096,77.817804,3.946621
2,3,6.350290,190.383738,14905.393852,5.537830,333.775777,446.840605,13.983567,67.817096,4.265233
3,4,9.578227,205.748742,33080.588825,5.659848,356.698301,333.069911,16.984961,68.906088,3.419239
4,5,7.300990,182.447697,29136.338677,8.253015,333.775777,307.433303,8.730149,49.895342,4.596347
...,...,...,...,...,...,...,...,...,...,...
978,979,5.921247,200.943730,17397.402858,6.756200,279.202307,380.499818,11.255357,31.966297,3.746776
979,980,7.388519,201.057714,13921.146217,7.766495,333.775777,560.774729,14.467095,74.374018,4.409054
980,981,7.553845,212.264441,14319.401370,5.793012,362.852654,450.535910,18.176483,66.396293,4.374564
981,982,7.122637,183.402648,31295.902410,4.425026,333.775777,411.616070,14.066057,77.185792,3.750447
982,983,8.370440,231.442553,15063.814968,12.279374,333.775777,422.293819,15.027088,67.503004,3.210635

In [69]:
# Lee el archivo CSV
nombre_archivo = 'water_quality_train.csv'
data = pd.read_csv(nombre_archivo)

# Especifica el nombre de la columna que deseas eliminar
columna_a_eliminar = 'day'

# Elimina la columna del DataFrame
data = data.drop(columns=[columna_a_eliminar])

# Guarda el DataFrame actualizado en un nuevo archivo CSV
nuevo_nombre_archivo = 'water_quality_train.csv'
data.to_csv(nuevo_nombre_archivo, index=False)

print(f"Columna '{columna_a_eliminar}' eliminada y archivo guardado como '{nuevo_nombre_archivo}'.")

Columna 'day' eliminada y archivo guardado como 'water_quality_train.csv'.

In [70]:
data = pd.read_csv('water_quality_train.csv')
# Agrega una nueva columna llamada 'day' con valores del 1 al nÃºmero de filas
num_filas = len(data)
data.insert(0, 'day', range(1, num_filas + 1))

# Guarda el DataFrame modificado de nuevo en un archivo CSV
nuevo_archivo_csv = 'water_quality_train.csv'
data.to_csv(nuevo_archivo_csv, index=False)

print("Columna 'day' agregada al principio exitosamente.")

Columna 'day' agregada al principio exitosamente.